### ISSUE TITLE
Acr.DeviceInfo error while using it with Xamarin.Forms

### ISSUE THREAD

**Issue by danieltrs** [aritchie/localization#1]
I've got the following error _[deviceinfo] Platform implementation not found.  Have you added a nuget reference to your platform project?_ when the autofac container is built in the PCL project.

`builder.Register(x => DeviceInfo.App).As<IApp>().SingleInstance();`

In the same autofac module is registered an AutoActivate service where the _Acr.DeviceInfo.IApp_ is injected using the service constructor.

`builder.RegisterType<LocalizationService>().AsImplementedInterfaces().AutoActivate().SingleInstance();`

The Acr.DeviceInfo and Acr.Localization references were added in both platform, iOS and Droid projects.

**Comment by aritchie** [comment]
Localization is not officially supported.  Run it at your own risk.  I have nothing called LocalizationService either.

In any case, this is a deviceinfo issue.  That error message will only come up if the PCL is being referenced and not the platform version.

**Comment by danieltrs** [comment]
The LocalizatioService is my class where the IApp is injected. However, I will try to reinstall the  packages.

**Comment by danieltrs** [comment]
I've manage to solve the issue and the problem was indeed the one you described above. The solution was to move the autofac container builder to each platform.

**Comment by aritchie** [comment]
I'm happy your issue is resolved, however, it doesn't make sense.  I register on the container builder like this all the time.

**Comment by danieltrs** [comment]
Initially the container build was made in the PCL project when the Application was instantiated. I have added the Acr.DeviceInfo package to all 3 projects - iOS, Droid and PCL. Probably, since the container was build in the PCL, the DeviceInfo PCL version was used instead the platform specific.
